name: Multi_Runners

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main


jobs:
  job1:
    name: First Job
    runs_on: ubuntu-latest
    steps:
      - name: Print welcome
        run: echo "Welcome to my world!"

  job2:
    name: Second Job
    runs_on: windows-latest
    steps:
      - name: Print welcome
        run: "Get-ChildItem Env: | Sort-Object Name"

  job1:
    name: Third Job
    runs_on: macos-latest
    steps:
      - name: Print welcome
        run: echo "Welcome to my world!"


  job1:
    name: Last Job
    runs_on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Print environment variables
        run: env | sort


